targets:
  $default:
    builders:
      scale_codec_serializable:
        enabled: true
        generate_for:
          - example/*

      source_gen|combining_builder:
        options:
          ignore_for_file:
          - unused_element

builders:
  scale_codec_serializable:
    import: "package:scale_codec_serializable/builder.dart"
    builder_factories: ["scaleCodecBuilder"]
    build_extensions: {".dart": [".g.dart"] }
    build_to: cache
    auto_apply: dependents
    applies_builders: ["source_gen|combining_builder"]