targets:
  $default:
    builders:
      scale_codec_serializable|scale_codec_annotation:
        enabled: true

builders:
  scale_codec_serializable:
    import: "package:scale_codec_serializable/builder.dart"
    builder_factories: ["scaleCodecSerializable"]
    build_extensions: {".dart": [".g.dart"] }
    build_to: cache
    auto_apply: dependents
    applies_builders: ["source_gen|combining_builder"]