name: scale_codec_serializable
description: >-
  Automatically generate code for converting Substrate metadata.
version: 1.0.0
publish_to: none # Uncoment this line when scale_codec_annotation is published

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  analyzer: ^4.6.0
  scale_codec_annotation:
    path: ../scale_codec_annotation/
  source_gen: ^1.2.2
  build: ^2.3.0
  meta: ^1.3.0
  source_helper: ^1.3.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.2.0
