name: polkadart_scale_codec
description: polkadart_scale_codec description
version: 1.0.0
homepage: https://github.com/rankanizer/polkadart

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  utility: ^1.0.2 # MIT
  convert: ^3.0.2 # BSD-3-Clause

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
