name: scale_codec_annotation
description: >-
  Classes and helper functions that support Scale Codec code generation via the
  `polkadart_scale_codec` package.
version: 1.0.0

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
